export const ADD_INFO_SUCCESS='ADD_INFO_SUCCESS';
export const ADD_INFO_REQUEST='ADD_INFO_REQUEST'
export const ADD_INFO_FAIL='ADD_INFO_FAIL'
export const LIST_INFO_REQUEST='LIST_INFO_REQUEST';
export const LIST_INFO_SUCCESS='LIST_INFO_SUCCESS';
export const LIST_INFO_FAIL='LIST_INFO_FAIL';

export const DEL_INFO_BYID_REQUEST='DEL_INFO_BYID_REQUEST';
export const DEL_INFO_BYID_SUCCESS='DEL_INFO_BYID_SUCCESS';
export const DEL_INFO_BYID_FAIL='DEL_INFO_BYID_FAIL'

export const DEL_SELECTED_ITEM='DEL_SELECTED_ITEM';
export const CHANGE_CHECKED_STATUS='CHANGE_CHECKED_STATUS';
export const CHANGE_ALL_CHECKED_STATUS = 'CHANGE_ALL_CHECKED_STATUS';
