export const ADD_INFO_ITEM='ADD_TODO_ITEM';
export const DEL_INFO_ITEM='DEL_TODO_ITEM';
export const DEL_SELECTED_ITEM='DEL_SELECTED_ITEM';
export const CHANGE_CHECKED_STATUS='CHANGE_CHECKED_STATUS';
export const CHANGE_ALL_CHECKED_STATUS = 'CHANGE_ALL_CHECKED_STATUS';
